### ISSUE TITLE
Change chunk icon depend on how performance consuming it is

### ISSUE THREAD

**Issue by LeeGodSRC** [Imanity-Software/ImanityChunkAnalyzerAddon#1]
Having every chunk display as name tag looks messy imo
This example here where redstone block = too performance consume, iron block = regular, and glass for literal to none performance consume feels better for me

![image](https://user-images.githubusercontent.com/36093806/141286567-39ef4d1e-85a4-4457-baca-fc5b4279a6f0.png)

**Comment by Whizyyy** [comment]
Done
