### ISSUE TITLE
Changing text color depend on how massive the number is, and format decimal to 3 digits only

### ISSUE THREAD

**Issue by LeeGodSRC** [Imanity-Software/ImanityChunkAnalyzerAddon#2]
Right now all the numbers are white and decimal aren't filtered which can looks very messy for new users
![image](https://user-images.githubusercontent.com/36093806/141286965-d96f3f0f-c96a-4104-9490-bdae7457993c.png)

Having the number being red, yellow, and white would feels better imo

**Comment by Whizyyy** [comment]
Done
