### ISSUE TITLE
Lack of ability to select entity / tile entity type for anaylze target

### ISSUE THREAD

**Issue by LeeGodSRC** [Imanity-Software/ImanityChunkAnalyzerAddon#3]
ChunkAnalyzer in ImanitySpigot3 contains the ability to pick entity type / tile entity type to be the target of the anaylze target
But in this addon you don't seems to have a way to select it

My idea is whenever you change sort target to entities / tile entities
A new button will appear right after the sort target button
And click it will lead you into a menu for example

![image](https://user-images.githubusercontent.com/36093806/141287516-4c6a71df-b258-40c2-9ccc-53603c54d483.png)
![image](https://user-images.githubusercontent.com/36093806/141287594-bfcc2dd0-1d33-46d8-a1ee-4c55b130055b.png)

glass will be all, and you can pick the entity / tile entity for target

**Comment by Whizyyy** [comment]
Done
