### ISSUE TITLE
Don't use enum as name, use a properly display name for both sort target and sort method

### ISSUE THREAD

**Issue by LeeGodSRC** [Imanity-Software/ImanityChunkAnalyzerAddon#4]
![image](https://user-images.githubusercontent.com/36093806/141287894-ab315585-7826-4247-a09a-3f6742adc388.png)
BLOCK_OPERATION to Block Operation

![image](https://user-images.githubusercontent.com/36093806/141287933-688c5e28-a80e-4629-9753-da9fd28ae186.png)
BY_AVG to By Average

For example

**Comment by Whizyyy** [comment]
Done
